#pragma once
#include <dxgiformat.h>
#include <cstdint>

constexpr uint32_t GBUFFER_TEXTURES_NUM = 4; // Total number of gbuffer render targets

enum GBUFFER_RENDER_TARGETS_FORMAT_MAPPINGS
{
	ALBEDO = 0,
	NORMAL = 1,
	ROUGH_METAL = 2,
	WORLDPOS_DEPTH = 3
};

constexpr DXGI_FORMAT FORMAT_ALBEDO = DXGI_FORMAT_R16G16B16A16_FLOAT;
constexpr DXGI_FORMAT FORMAT_NORMAL = DXGI_FORMAT_R16G16B16A16_FLOAT;
constexpr DXGI_FORMAT FORMAT_ROUGH_METAL = DXGI_FORMAT_R16G16B16A16_FLOAT;
constexpr DXGI_FORMAT FORMAT_WORLDPOS_DEPTH = DXGI_FORMAT_R32G32B32A32_FLOAT;
