#pragma once
#define GBUFFER_TEXTURES_NUM 4 // Total number of gbuffer render targets

enum GBUFFER_RENDER_TARGETS_FORMAT_MAPPINGS
{
	ALBEDO = 0,
	NORMAL = 1,
	ROUGH_METAL = 2,
	WORLDPOS_DEPTH = 3
};

enum GBUFFER_RENDER_TARGETS_FORMAT
{
	FORMAT_ALBEDO = DXGI_FORMAT_R8G8B8A8_UNORM,
	FORMAT_NORMAL = DXGI_FORMAT_R10G10B10A2_UNORM,
	FORMAT_ROUGH_METAL = DXGI_FORMAT_R8G8B8A8_UNORM,
	FORMAT_WORLDPOS_DEPTH = DXGI_FORMAT_R16G16B16A16_FLOAT
};
